FROM alpine:latest
RUN apk update
RUN apk add build-base git file ncurses-dev readline-dev util-linux-dev glib-dev raptor2-dev redland-dev rasqal-dev autoconf automake libtool
WORKDIR /tmp
RUN git clone https://github.com/4store/4store
WORKDIR /tmp/4store
RUN ./autogen.sh
RUN ./configure --prefix=/4store
RUN make
RUN mkdir /output
RUN make install DESTDIR=/output
